# Generated by Django 2.2 on 2021-05-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=200)),
                ('Photo', models.ImageField(upload_to='images/others')),
                ('Price', models.IntegerField()),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
