# Generated by Django 2.2 on 2021-05-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_item',
            name='DateTime',
            field=models.DateTimeField(),
        ),
    ]
