# Generated by Django 2.2 on 2021-05-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20210517_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_item',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/others'),
        ),
    ]
