# Generated by Django 2.2 on 2021-05-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20210518_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_item',
            name='Photo',
            field=models.ImageField(upload_to='images/others'),
        ),
    ]
