# Generated by Django 2.2 on 2021-05-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20210518_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_item',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
