# Generated by Django 2.2 on 2021-05-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_bid_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_item',
            name='Description',
            field=models.TextField(max_length=500),
        ),
    ]
