# Generated by Django 2.2 on 2021-05-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_auto_20210521_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_item',
            name='Description',
            field=models.TextField(),
        ),
    ]
