# Generated by Django 2.2 on 2021-05-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/images/profile/profile.png', null=True, upload_to='images/profile'),
        ),
    ]
